# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTrello2():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_trello2(self):
    # Test name: Trello2
    # Step # | name | target | value | comment
    # 1 | open | /logged-out |  | 
    self.driver.get("https://trello.com/logged-out")
    # 2 | setWindowSize | 950x691 |  | 
    self.driver.set_window_size(950, 691)
  
