# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTrello5():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_trello5(self):
    # Test name: trello5
    # Step # | name | target | value | comment
    # 1 | open | /login |  | 
    self.driver.get("https://trello.com/login")
    # 2 | setWindowSize | 1366x704 |  | 
    self.driver.set_window_size(1366, 704)
    # 3 | click | id=user |  | 
    self.driver.find_element(By.ID, "user").click()
    # 4 | type | id=user | moazam.rana@ucp.edu.pk | 
    self.driver.find_element(By.ID, "user").send_keys("moazam.rana@ucp.edu.pk")
    # 5 | click | id=password |  | 
    self.driver.find_element(By.ID, "password").click()
    # 6 | type | id=password | return0; | 
    self.driver.find_element(By.ID, "password").send_keys("return0;")
    # 7 | click | id=login |  | 
    self.driver.find_element(By.ID, "login").click()
    # 8 | mouseDownAt | id=content | 1365,262 | 
    element = self.driver.find_element(By.ID, "content")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).click_and_hold().perform()
    # 9 | mouseMoveAt | id=content | 1365,262 | 
    element = self.driver.find_element(By.ID, "content")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 10 | mouseUpAt | id=content | 1365,262 | 
    element = self.driver.find_element(By.ID, "content")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).release().perform()
    # 11 | click | css=.boards-page-board-section:nth-child(3) .\_1B5Z7PBtTwhVM0:nth-child(1) span:nth-child(1) |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".boards-page-board-section:nth-child(3) .\\_1B5Z7PBtTwhVM0:nth-child(1) span:nth-child(1)").click()
    # 12 | mouseOver | css=.\_27QKbGhxDkdNHq > .\_1T7jXM3PAP_MoF > .pgEbaAFZBA0N5R:nth-child(3) .\_3qwe2tMMFonNvf |  | 
    element = self.driver.find_element(By.CSS_SELECTOR, ".\\_27QKbGhxDkdNHq > .\\_1T7jXM3PAP_MoF > .pgEbaAFZBA0N5R:nth-child(3) .\\_3qwe2tMMFonNvf")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 13 | click | css=.\_27QKbGhxDkdNHq > .\_1T7jXM3PAP_MoF > .pgEbaAFZBA0N5R:nth-child(3) .\_3qwe2tMMFonNvf |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".\\_27QKbGhxDkdNHq > .\\_1T7jXM3PAP_MoF > .pgEbaAFZBA0N5R:nth-child(3) .\\_3qwe2tMMFonNvf").click()
    # 14 | mouseOut | css=.\_27QKbGhxDkdNHq > .\_1T7jXM3PAP_MoF > .pgEbaAFZBA0N5R:nth-child(3) .\_3qwe2tMMFonNvf |  | 
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    # 15 | mouseDownAt | id=content | 1365,85 | 
    element = self.driver.find_element(By.ID, "content")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).click_and_hold().perform()
    # 16 | mouseMoveAt | id=content | 1365,85 | 
    element = self.driver.find_element(By.ID, "content")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 17 | mouseUpAt | id=content | 1365,85 | 
    element = self.driver.find_element(By.ID, "content")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).release().perform()
    # 18 | click | css=.\_1T7jXM3PAP_MoF > .pgEbaAFZBA0N5R:nth-child(1) .\_3qwe2tMMFonNvf |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".\\_1T7jXM3PAP_MoF > .pgEbaAFZBA0N5R:nth-child(1) .\\_3qwe2tMMFonNvf").click()
    # 19 | mouseDownAt | id=content | 1365,271 | 
    element = self.driver.find_element(By.ID, "content")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).click_and_hold().perform()
    # 20 | mouseMoveAt | id=content | 1365,271 | 
    element = self.driver.find_element(By.ID, "content")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 21 | mouseUpAt | id=content | 1365,271 | 
    element = self.driver.find_element(By.ID, "content")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).release().perform()
    # 22 | mouseDownAt | id=content | 1365,-57 | 
    element = self.driver.find_element(By.ID, "content")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).click_and_hold().perform()
    # 23 | mouseMoveAt | id=content | 1365,-57 | 
    element = self.driver.find_element(By.ID, "content")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 24 | mouseUpAt | id=content | 1365,-57 | 
    element = self.driver.find_element(By.ID, "content")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).release().perform()
    # 25 | click | css=.\_3u1GtvBzzFOTuk |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".\\_3u1GtvBzzFOTuk").click()
    # 26 | click | css=.\_2Tz6APAhsLuGzg |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".\\_2Tz6APAhsLuGzg").click()
    # 27 | click | css=li:nth-child(2) .\_1uK2vQ_aMRS2NU |  | 
    self.driver.find_element(By.CSS_SELECTOR, "li:nth-child(2) .\\_1uK2vQ_aMRS2NU").click()
    # 28 | click | css=.\_24AWINHReYjNBf |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".\\_24AWINHReYjNBf").click()
    # 29 | click | css=li:nth-child(8) .\_1uK2vQ_aMRS2NU |  | 
    self.driver.find_element(By.CSS_SELECTOR, "li:nth-child(8) .\\_1uK2vQ_aMRS2NU").click()
  
